# Generated by Django 4.2.4 on 2023-08-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="magang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Judul", models.CharField(max_length=50)),
                ("Jurusan", models.CharField(max_length=50)),
                ("Deskripsi", models.TextField()),
                ("Deadline", models.DateField()),
                ("Publish", models.DateTimeField()),
                ("is_closed", models.BooleanField(blank=None, default=True, null=None)),
                ("file", models.FileField(upload_to="upload/")),
                (
                    "Nama_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.magang"
                    ),
                ),
            ],
        ),
    ]
