# Generated by Django 4.2.4 on 2023-08-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_user_alter_magang_nama_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nama",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
